### ISSUE TITLE
src/dashboard.tsx:20:26 - error TS18047: 'pages' is possibly 'null'

### ISSUE THREAD

**Issue by xiang578** [CorrectRoadH/logseq-plugins-develop-tutorial#3]
学习 https://correctroad.gitbook.io/logseq-plugins-in-action/chapter-1/make-a-toolbar-dashboard 过程中，直接复制您提供的代码，然后编译出现下面报错，能帮忙看一下怎么解决吗？

```
src/dashboard.tsx:18:5 - error TS2304: Cannot find name 'useEffect'.

18     useEffect(()=>{
       ~~~~~~~~~

src/dashboard.tsx:20:26 - error TS18047: 'pages' is possibly 'null'.

20             setPageCount(pages.length);
                            ~~~~~


Found 2 errors in the same file, starting at: src/dashboard.tsx:18

 ELIFECYCLE  Command failed with exit code 2.
```

**Comment by yangyangnote** [comment]
useEffect 报错   在项目里导入就行了  import { useEffect } from 'react';

pages 报错还没找到原因 @CorrectRoadH

**Comment by yangyangnote** [comment]
@xiang578   pages的问题也解决了

这个问题的原因可能是在该 useEffect 函数执行之前，window.logseq.Editor 对象还没有完成初始化，导致 getAllPages() 方法返回的 pages 值为 null。

如果这样的话，可以在 useEffect 函数的依赖数组中加入 window.logseq.Editor ，以确保在其完成初始化后再调用 getAllPages() 方法：

useEffect(()=>{
if (window.logseq.Editor) {
window.logseq.Editor.getAllPages().then(pages => {
if (pages) {
setPageCount(pages.length);
}
});
}
},[window.logseq.Editor])

**Comment by CorrectRoadH** [comment]
抱歉这么晚才看到这个issue。这个问题的解决方法确实如yangyangnote所说。
这里在感谢@yangyangnote。然后也更新了本章的教程，使用的楼上的代码。

**Comment by CorrectRoadH** [comment]
我在这里提供了现成能跑的代码，如果还有遇到问题，可以对照一下。
https://github.com/CorrectRoadH/logseq-plugins-develop-tutorial/tree/main/code/logseq-dashboard

**Comment by yangyangnote** [comment]
@CorrectRoadH  为了配套视频讲解  单独把修改过的代码存放在  https://github.com/yangyangnote/logseqcounts 仓库里,并标明出处,仅作交流使用
如果 有侵权,请指出,会立马删除😄

**Comment by CorrectRoadH** [comment]
> @CorrectRoadH 为了配套视频讲解 单独把修改过的代码存放在 https://github.com/yangyangnote/logseqcounts 仓库里,并标明出处,仅作交流使用
> 如果 有侵权,请指出,会立马删除😄

没有问题的🙋‍♂️
